//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmSalesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLogin
    {
        public string CrmUserId { get; set; }
        public string Password { get; set; }
        public string CrmWebServiceUrl { get; set; }
    }
}
