//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmSalesProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmSalesProjectEntities : DbContext
    {
        public CrmSalesProjectEntities()
            : base("name=CrmSalesProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CrmAccount> CrmAccounts { get; set; }
        public virtual DbSet<CrmContact> CrmContacts { get; set; }
        public virtual DbSet<CrmLogin> CrmLogins { get; set; }
    }
}
